### ISSUE TITLE
Application error is shown when try to access URL

### ISSUE THREAD

**Issue by fabasoad** [shubham-lohan/leetcode-visualizer#1]
## Steps to reproduce

1. Open browser
2. Go to `https://leetcode-visualizer.herokuapp.com`
3. See the page

## Expected behavior

Valid body should be shown

## Actual behavior

Application error is shown:

![Screen Shot 2022-12-03 at 18 17 25](https://user-images.githubusercontent.com/2127723/205433714-658708fe-6e11-4594-b9dc-bbbfd1c292e5.png)

**Comment by shubham-lohan** [comment]
Heroku free tier plan has been expired, looking for better alternative.Meanwhile you can setup this locally
